"""
Generates 03-seed.sql: fictional customers, orders, lines and invoices for the legacy database.

Deterministic (fixed random seed) so the legacy API, the migrator's verification report and the
contract tests always see the same data. It also plants the kind of dirty data real legacy
databases have, so the migration has something to handle:
  - emails with stray spaces / upper case, mixed phone formats
  - IsActive flags 'Y', 'N' and lower-case 'y'
  - a few orders whose TotalAmt doesn't match the sum of their lines (an old bug)
  - invoices with PaidFlag = 1 but no PaidDt
Run:  python generate_seed.py  (rewrites 03-seed.sql)
"""
import random
from datetime import datetime, timedelta
from decimal import Decimal
from pathlib import Path

rng = random.Random(2019)

COMPANIES = [
    ("CPRE", "Chao Phraya Rice Exports", "TH"), ("IRWT", "Irrawaddy Textiles", "MM"),
    ("LCEL", "Lion City Electronics", "SG"), ("SGCT", "Saigon Coffee Traders", "VN"),
    ("KVAP", "Klang Valley Auto Parts", "MY"), ("JVFB", "Java Furniture Builders", "ID"),
    ("ANDM", "Andaman Seafood Co.", "TH"), ("MKGF", "Mekong Garment Factory", "VN"),
    ("SMRT", "Siam Rubber Trading", "TH"), ("BRNT", "Borneo Timber Supply", "MY"),
    ("PNKS", "Penang Kitchenware", "MY"), ("YGNP", "Yangon Paper Mills", "MM"),
    ("HCMT", "Ho Chi Minh Toys", "VN"), ("CMTT", "Chiang Mai Teak Traders", "TH"),
    ("SURC", "Surabaya Ceramics", "ID"), ("BKKS", "Bangkok Solar Systems", "TH"),
    ("MDLY", "Mandalay Handicrafts", "MM"), ("DNGF", "Da Nang Fishing Supply", "VN"),
    ("KLMD", "KL Medical Devices", "MY"), ("BTMF", "Batam Machine Fabrication", "ID"),
    ("PHKT", "Phuket Resort Supplies", "TH"), ("HAIP", "Haiphong Steel Pipes", "VN"),
    ("SNGF", "Straits Fine Foods", "SG"), ("RYGL", "Rayong Glassworks", "TH"),
    ("KHNS", "Khon Kaen Sugar", "TH"),
]
PORTS = ["THLCH", "THBKK", "SGSIN", "MYPKG", "VNSGN", "IDJKT", "MMRGN", "CNSHA", "HKHKG", "JPTYO"]
ITEMS = [
    ("Ocean freight 20GP", 650, 1400), ("Ocean freight 40HC", 1100, 2600), ("Customs clearance", 80, 220),
    ("Trucking to port", 120, 380), ("Warehouse handling", 40, 160), ("Cargo insurance", 30, 120),
    ("Documentation fee", 25, 60), ("Fumigation", 60, 140), ("Reefer plug-in (per day)", 35, 70),
]
REMARKS = [None, None, "Fragile goods", "Call consignee before delivery", "Reefer -18C", "Urgent",
           "Customer will collect from port", None]


def q(value):
    """SQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, (int, Decimal)):
        return str(value)
    if isinstance(value, datetime):
        return "'" + value.strftime("%Y-%m-%dT%H:%M:%S") + "'"
    return "N'" + str(value).replace("'", "''") + "'"


def money(low, high):
    return Decimal(rng.randint(low * 100, high * 100)) / 100


def email_for(code, name, i):
    base = f"ops@{code.lower()}.example.com"
    if i % 9 == 4:
        return f"  {base.upper()} "        # dirty: whitespace + upper case
    if i % 11 == 7:
        return None
    return base


def phone_for(country, i):
    digits = "".join(str(rng.randint(0, 9)) for _ in range(8))
    prefix = {"TH": "+66", "SG": "+65", "MY": "+60", "VN": "+84", "ID": "+62", "MM": "+95"}[country]
    styles = [f"{prefix} {digits[:4]} {digits[4:]}", f"0{digits}", f"({prefix}) {digits}", None]
    return styles[i % 4]


lines_out = [
    "/* Generated by generate_seed.py. Fictional data only. Local (Bangkok) timestamps, as the legacy app stored them. */",
    "SET NOCOUNT ON;",
    "SET QUOTED_IDENTIFIER ON;",
    "SET IDENTITY_INSERT dbo.tblCustomer ON;",
]

start = datetime(2019, 3, 1, 9, 0, 0)
for i, (code, name, country) in enumerate(COMPANIES, start=1):
    created = start + timedelta(days=rng.randint(0, 900), minutes=rng.randint(0, 600))
    active = "N" if i % 8 == 0 else ("y" if i % 10 == 3 else "Y")   # dirty: lower-case flag
    lines_out.append(
        "INSERT INTO dbo.tblCustomer (CustID, CustCode, CustNm, Email, Phone, Country, IsActive, CreatedDt) VALUES "
        f"({i}, {q(code)}, {q(name)}, {q(email_for(code, name, i))}, {q(phone_for(country, i))}, {q(country)}, {q(active)}, {q(created)});"
    )
lines_out.append("SET IDENTITY_INSERT dbo.tblCustomer OFF;")

order_id = 0
line_id = 0
invoice_id = 0
order_lines, line_lines, invoice_lines = [], [], []
seq_by_year = {}
for _ in range(160):
    order_id += 1
    cust = rng.randint(1, len(COMPANIES))
    ordered = datetime(2023, 1, 5, 8, 0) + timedelta(days=rng.randint(0, 1330), minutes=rng.randint(0, 600))
    seq_by_year[ordered.year] = seq_by_year.get(ordered.year, 0) + 1
    order_no = f"ORD-{ordered.year}-{seq_by_year[ordered.year]:06d}"
    age_days = (datetime(2026, 9, 1) - ordered).days
    status = 4 if rng.random() < 0.07 else (3 if age_days > 30 else rng.choice([1, 2, 2, 3]))
    origin = rng.choice(PORTS)
    dest = rng.choice([p for p in PORTS if p != origin])

    total = Decimal(0)
    for line_no in range(1, rng.randint(1, 4) + 1):
        line_id += 1
        descr, low, high = rng.choice(ITEMS)
        qty = rng.randint(1, 3)
        price = money(low, high)
        total += qty * price
        line_lines.append(
            "INSERT INTO dbo.tblOrderLine (LineID, OrderID, LineNum, Descr, Qty, UnitPrice) VALUES "
            f"({line_id}, {order_id}, {line_no}, {q(descr)}, {qty}, {price});"
        )
    if order_id in (17, 58, 121):
        total += Decimal("10.00")   # dirty: an old rounding bug left these totals off by $10

    order_lines.append(
        "INSERT INTO dbo.tblOrder (OrderID, OrderNo, CustID, OrderDt, Status, Origin, Dest, Remarks, TotalAmt, Curr) VALUES "
        f"({order_id}, {q(order_no)}, {cust}, {q(ordered)}, {status}, {q(origin)}, {q(dest)}, {q(rng.choice(REMARKS))}, {total}, 'USD');"
    )

    if status in (2, 3):
        invoice_id += 1
        inv_date = ordered + timedelta(days=rng.randint(1, 5))
        due = inv_date + timedelta(days=30)
        paid = status == 3 and rng.random() < 0.8
        paid_dt = inv_date + timedelta(days=rng.randint(3, 40)) if paid else None
        if invoice_id in (9, 44):
            paid, paid_dt = True, None   # dirty: flagged paid but no paid date
        invoice_lines.append(
            "INSERT INTO dbo.tblInvoice (InvID, OrderID, InvNo, InvDt, DueDt, Amount, PaidFlag, PaidDt) VALUES "
            f"({invoice_id}, {order_id}, {q(f'INV-{inv_date.year}-{invoice_id:05d}')}, {q(inv_date)}, {q(due)}, {total}, {1 if paid else 0}, {q(paid_dt)});"
        )

lines_out += ["SET IDENTITY_INSERT dbo.tblOrder ON;", *order_lines, "SET IDENTITY_INSERT dbo.tblOrder OFF;"]
lines_out += ["SET IDENTITY_INSERT dbo.tblOrderLine ON;", *line_lines, "SET IDENTITY_INSERT dbo.tblOrderLine OFF;"]
lines_out += ["SET IDENTITY_INSERT dbo.tblInvoice ON;", *invoice_lines, "SET IDENTITY_INSERT dbo.tblInvoice OFF;"]
next_this_year = seq_by_year.get(2026, 0) + 1
lines_out.append(f"INSERT INTO dbo.tblSequence (SeqName, NextVal) VALUES ('ORDER', {next_this_year});")

Path(__file__).with_name("03-seed.sql").write_text("\n".join(lines_out) + "\n", encoding="utf-8")
print(f"customers={len(COMPANIES)} orders={order_id} lines={line_id} invoices={invoice_id}")
